services:
  crud-server:
    build:
      context: .
      target: final
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - app_net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app_net:
    name: crud-network
